{
  "contest": 278,
  "handle": "Stormreckson",
  "risk": "3",
  "title": "Potential Misuse of \"sync\" Function can lead to Denial of service ",
  "issueId": 51,
  "issueUrl": "https://github.com/code-423n4/2023-08-dopex-findings/issues/51"
}